// campus.constants.ts
export const CAMPUS_LIST: string[] = [
  'Campus Abelardo Luz',
  'Campus Abreu e Lima',
  'Campus Acaraú',
  'Campus Acopiara',
  'Campus Açailândia',
  'Campus Afogados da Ingazeira',
  'Campus Águas Lindas',
  'Campus Alcântara',
  'Campus Alegrete',
  'Campus Almenara',
  'Campus Alvorada',
  'Campus Amajari',
  'Campus Anápolis',
  'Campus Angical',
  'Campus Aparecida de Goiânia',
  'Campus Apodi',
  'Campus Aquidauana',
  'Campus Araçuaí',
  'Campus Aracati',
  'Campus Aracruz',
  'Campus Araguaína',
  'Campus Araguatins',
  'Campus Arapongas',
  'Campus Arapiraca',
  'Campus Araquari',
  'Campus Araxá',
  'Campus Arinos',
  'Campus Ariquemes',
  'Campus Astorga',
  'Campus Avaré',
  'Campus Bacabal',
  'Campus Bagé',
  'Campus Bambuí',
  'Campus Barbacena',
  'Campus Barra de São Francisco',
  'Campus Barra do Corda',
  'Campus Barra do Garças',
  'Campus Barracão',
  'Campus Barreiras',
  'Campus Barreirinhas',
  'Campus Barreiros',
  'Campus Barretos - Sede',
  'Campus Batalha',
  'Campus Baturité',
  'Campus Belo Jardim',
  'Campus Bento Gonçalves',
  'Campus Betim',
  'Campus Birigui',
  'Campus Blumenau',
  'Campus Boa Viagem',
  'Campus Boa Vista',
  'Campus Boa Vista Zona Oeste',
  'Campus Boituva',
  'Campus Bom Jesus do Itabapoana',
  'Campus Bragança Paulista',
  'Campus Brasília',
  'Campus Buriticupu',
  'Campus Cabedelo',
  'Campus Cabo de Santo Agostinho',
  'Campus Cabo Frio',
  'Campus Cacoal',
  'Campus Cachoeiro de Itapemirim',
  'Campus Cáceres - Prof. Olegário Baldo',
  'Campus Caicó',
  'Campus Cajazeiras',
  'Campus Camaquã',
  'Campus Camboriu',
  'Campus Cambuci',
  'Campus Camocim',
  'Campus Campina Grande',
  'Campus Campinas',
  'Campus Campo Grande',
  'Campus Campo Largo',
  'Campus Campo Maior',
  'Campus Campo Novo do Parecis',
  'Campus Campos Belos',
  'Campus Campos Centro',
  'Campus Campos do Jordão',
  'Campus Campos Guarus',
  'Campus Canindé',
  'Campus Canoas',
  'Campus Canguaretama',
  'Campus Capanema',
  'Campus Capivari',
  'Campus Caraguatatuba',
  'Campus Cariacica',
  'Campus Carmo de Minas',
  'Campus Caruaru',
  'Campus Cascavel',
  'Campus Catanduva',
  'Campus Catolé do Rocha',
  'Campus Caucaia',
  'Campus Ceará-Mirim',
  'Campus Cedro',
  'Campus Ceilândia',
  'Campus Centro-Serrano',
  'Campus Ceres',
  'Campus Charqueadas',
  'Campus Cidade de Goiás',
  'Campus Coari',
  'Campus Cocal',
  'Campus Codó',
  'Campus Coelho Neto',
  'Campus Colatina',
  'Campus Colinas do Tocantins',
  'Campus Colorado do Oeste',
  'Campus Colombo',
  'Campus Concordia',
  'Campus Confresa',
  'Campus Congonhas',
  'Campus Contagem',
  'Campus Coronel Vivida',
  'Campus Corrente',
  'Campus Corumbá',
  'Campus Coruripe',
  'Campus Coxim',
  'Campus Crateús',
  'Campus Crato',
  'Campus Cristalina',
  'Campus Cubatão',
  'Campus Cuiabá - Bela Vista',
  'Campus Cuiabá Cel. Octayde Jorge da Silva',
  'Campus Currais Novos',
  'Campus Curitiba',
  'Campus Curvelo',
  'Campus Caxias',
  'Campus Caxias do Sul',
  'Campus Dianópolis',
  'Campus Diamantina',
  'Campus Divinópolis',
  'Campus Dourados',
  'Campus Erechim',
  'Campus Esperança',
  'Campus Estrutural',
  'Campus Farroupilha',
  'Campus Feliz',
  'Campus Floresta',
  'Campus Floriano',
  'Campus Formiga',
  'Campus Formosa',
  'Campus Formoso do Araguaia',
  'Campus Fortaleza',
  'Campus Foz do Iguaçu',
  'Campus Fraiburgo',
  'Campus Gama',
  'Campus Garanhuns',
  'Campus Goiânia',
  'Campus Goiânia Oeste',
  'Campus Goioere',
  'Campus Governador Valadares',
  'Campus Grajaú',
  'Campus Gravataí',
  'Campus Guarabira',
  'Campus Guarapari',
  'Campus Guarulhos',
  'Campus Guajará Mirim',
  'Campus Gurupi',
  'Campus Horizonte',
  'Campus Hortolândia',
  'Campus Humaita',
  'Campus Ibirama',
  'Campus Ibirité',
  'Campus Ibirubá',
  'Campus Ibatiba',
  'Campus Igarassu',
  'Campus Iguatu',
  'Campus Ilha Solteira',
  'Campus Imperatriz',
  'Campus Inconfidentes',
  'Campus Inhumas',
  'Campus Iporá',
  'Campus Ipojuca',
  'Campus Ipanguaçu',
  'Campus Irati',
  'Campus Itabaiana',
  'Campus Itaborai',
  'Campus Itacoatiara',
  'Campus Itajubá',
  'Campus Itapecuru Mirim',
  'Campus Itaperuna',
  'Campus Itapetininga',
  'Campus Itapina',
  'Campus Itapipoca',
  'Campus Itaporanga',
  'Campus Itaquaquecetuba',
  'Campus Itajaí',
  'Campus Ituiutaba',
  'Campus Itumbiara',
  'Campus Ivaipora',
  'Campus Jaboatão Dos Guararapes',
  'Campus Jacareí',
  'Campus Jacarezinho',
  'Campus Jaguaribe',
  'Campus Jaguari',
  'Campus Jaguariaiva',
  'Campus Janaúba',
  'Campus Januária',
  'Campus Jardim',
  'Campus Jaru',
  'Campus Jataí',
  'Campus Jí-paraná',
  'Campus João Câmara',
  'Campus João Pessoa',
  'Campus Juazeiro do Norte',
  'Campus Jucurutu',
  'Campus Juína',
  'Campus Juiz de Fora',
  'Campus Jundiaí',
  'Campus Júlio de Castilhos',
  'Campus Labrea',
  'Campus Lagoa da Confusão',
  'Campus Lajeado',
  'Campus Lajes',
  'Campus Laranjal do Jari',
  'Campus Leopoldina',
  'Campus Limoeiro do Norte',
  'Campus Linhares',
  'Campus Londrina',
  'Campus Luziânia',
  'Campus Luzerna',
  'Campus Macaé',
  'Campus Macapá',
  'Campus Maceio',
  'Campus Macau',
  'Campus Machado',
  'Campus Manacapuru',
  'Campus Manaus Centro',
  'Campus Manaus Distrito',
  'Campus Manaus Zona Leste',
  'Campus Manhuaçu',
  'Campus Maracanaú',
  'Campus Maragogi',
  'Campus Maranguape',
  'Campus Marechal Deodoro',
  'Campus Maricá',
  'Campus Matão',
  'Campus Maues',
  'Campus Mirinzal',
  'Campus Montanha',
  'Campus Monteiro',
  'Campus Montes Claros',
  'Campus Morada Nova',
  'Campus Morrinhos',
  'Campus Mossoró',
  'Campus Muriaé',
  'Campus Murici',
  'Campus Muzambinho',
  'Campus Natal - Central',
  'Campus Natal - Cidade Alta',
  'Campus Natal - Zona Leste (EaD)',
  'Campus Natal - Zona Norte',
  'Campus Naviraí',
  'Campus Nepomuceno',
  'Campus Nova Andradina',
  'Campus Nova Cruz',
  'Campus Nova Gameleira',
  'Campus Nova Suíça',
  'Campus Nova Venécia',
  'Campus Novo Paraíso',
  'Campus Oeiras',
  'Campus Oiapoque',
  'Campus Olinda',
  'Campus Osório',
  'Campus Ouricuri',
  'Campus Ouro Branco',
  'Campus Ouro Preto',
  'Campus Palmares',
  'Campus Palmas',
  'Campus Palmeira Dos Indios',
  'Campus Panambi',
  'Campus Paracatu',
  'Campus Paracuru',
  'Campus Paraíso do Tocantins',
  'Campus Paranaguá',
  'Campus Paranavai',
  'Campus Parelhas',
  'Campus Parintins',
  'Campus Parnaíba',
  'Campus Parnamirim',
  'Campus Passos',
  'Campus Passo Fundo',
  'Campus Patos',
  'Campus Patos de Minas',
  'Campus Patrocínio',
  'Campus Pau dos Ferros',
  'Campus Paulistana',
  'Campus Paulista',
  'Campus Pecém',
  'Campus Pedreiras',
  'Campus Pedro Afonso',
  'Campus Pedro II',
  'Campus Pelotas',
  'Campus Pelotas - Visconde da Graça',
  'Campus Penedo',
  'Campus Pesqueira',
  'Campus Petrolina',
  'Campus Petrolina Zona Rural',
  'Campus Picos',
  'Campus Picuí',
  'Campus Pinhais',
  'Campus Pinheiro',
  'Campus Piracicaba',
  'Campus Pirapora',
  'Campus Piranhas',
  'Campus Piripiri',
  'Campus Pirituba',
  'Campus Pitanga',
  'Campus Piúma',
  'Campus Planaltina',
  'Campus Poços de Caldas',
  'Campus Ponta Porã',
  'Campus Pontes e Lacerda',
  'Campus Porto Alegre',
  'Campus Porto Grande',
  'Campus Porto Nacional',
  'Campus Porto Velho Calama',
  'Campus Porto Velho Zona Norte',
  'Campus Posse',
  'Campus Pouso Alegre',
  'Campus Presidente Dutra',
  'Campus Presidente Epitácio',
  'Campus Presidente Figueiredo',
  'Campus Presidente Kennedy',
  'Campus Primavera do Leste',
  'Campus Princesa Isabel',
  'Campus Quedas do Iguaçu',
  'Campus Quissamã',
  'Campus Quixadá',
  'Campus Recanto das Emas',
  'Campus Recife',
  'Campus Registro',
  'Campus Restinga',
  'Campus Riacho Fundo',
  'Campus Ribeirão das Neves',
  'Campus Rio Branco',
  'Campus Rio de Janeiro',
  'Campus Rio do Sul',
  'Campus Rio Grande',
  'Campus Rio Largo',
  'Campus Rio Pomba',
  'Campus Rio Verde',
  'Campus Rolante',
  'Campus Rondonópolis',
  'Campus Sabará',
  'Campus Salgueiro',
  'Campus Salinas',
  'Campus Salto',
  'Campus Samambaia',
  'Campus Santa Cruz',
  'Campus Santa Inês',
  'Campus Santa Luzia',
  'Campus Santa Maria da Boa Vista',
  'Campus Santa Rita',
  'Campus Santa Rosa',
  'Campus Santa Rosa do Sul',
  'Campus Santa Teresa',
  'Campus Santana',
  'Campus Santana do Ipanema',
  'Campus Santana do Livramento',
  'Campus Santo Ângelo',
  'Campus Santo Antônio De Pádua',
  'Campus Santo Augusto',
  'Campus Santos Dumont',
  'Campus Sao Bento do Sul',
  'Campus Sao Francisco do Sul',
  'Campus Sao Miguel',
  'Campus Sao Miguel Dos Campos',
  'Campus São Borja',
  'Campus São Gabriel',
  'Campus São Gonçalo do Amarante',
  'Campus São João da Boa Vista',
  'Campus São João Da Barra',
  'Campus São João Del Rei',
  'Campus São João do Piauí',
  'Campus São João dos Patos',
  'Campus São João Evangelista',
  'Campus São José',
  'Campus São José de Ribamar',
  'Campus São José dos Campos',
  'Campus São Luís Centro Histórico',
  'Campus São Luís Maracanã',
  'Campus São Luís Monte Castelo',
  'Campus São Mateus',
  'Campus São Miguel Paulista',
  'Campus São Paulo',
  'Campus São Paulo do Potengi',
  'Campus São Raimundo das Mangabeiras',
  'Campus São Raimundo Nonato',
  'Campus São Roque',
  'Campus São Sebastião',
  'Campus São Vicente',
  'Campus São Vicente do Sul',
  'Campus Sapiranga',
  'Campus Sapucaia do Sul',
  'Campus Satuba',
  'Campus Senador Canedo',
  'Campus Serra',
  'Campus Serra Talhada',
  'Campus Sertão',
  'Campus Sertãozinho',
  'Campus Sobral',
  'Campus Sombrio',
  'Campus Sorocaba',
  'Campus Sorriso',
  'Campus Sousa',
  'Campus Suzano',
  'Campus Tabuleiro Do Norte',
  'Campus Tabatinga',
  'Campus Taguatinga',
  'Campus Tauá',
  'Campus Tefé',
  'Campus Telemaco Borba',
  'Campus Teófilo Otoni',
  'Campus Teresina Central',
  'Campus Teresina Zona Sul',
  'Campus Tianguá',
  'Campus Timóteo',
  'Campus Timon',
  'Campus Três Corações',
  'Campus Três Lagoas',
  'Campus Trindade',
  'Campus Tupã',
  'Campus Ubajara',
  'Campus Uberaba',
  'Campus Uberlândia',
  'Campus Uberlândia Centro',
  'Campus Umirim',
  'Campus Umuarama',
  'Campus União da Vitória',
  'Campus Uruguaiana',
  'Campus Uruaçu',
  'Campus Urucui',
  'Campus Urupema',
  'Campus Urutaí',
  'Campus Vacaria',
  'Campus Valenca',
  'Campus Valparaíso',
  'Campus Varginha',
  'Campus Várzea Grande',
  'Campus Venda Nova do Imigrante',
  'Campus Venâncio Aires',
  'Campus Veranópolis',
  'Campus Viana',
  'Campus Viamão',
  'Campus Viçosa',
  'Campus Videira',
  'Campus Vila Velha',
  'Campus Vilhena',
  'Campus Vitória',
  'Campus Vitória de Santo Antão',
  'Campus Votuporanga',
  'Campus Zé Doca',
  'Câmpus Araranguá',
  'Câmpus Caçador',
  'Câmpus Canoinhas',
  'Câmpus Chapecó',
  'Câmpus Criciúma',
  'Câmpus Florianópolis',
  'Câmpus Florianópolis-Continente',
  'Câmpus Garopaba',
  'Câmpus Gaspar',
  'Câmpus Itajaí',
  'Câmpus Jaraguá do SUL- RAU ( Geraldo Werninghaus)',
  'Câmpus Jaraguá do Sul',
  'Câmpus Joinville',
  'Câmpus Lages',
  'Câmpus Palhoça Bilíngue',
  'Câmpus São Carlos',
  'Câmpus São José',
  'Câmpus São Lourençco do Oeste',
  'Câmpus São Miguel do Oeste',
  'Câmpus Tubarão',
  'Câmpus Xanxerê',
  'Câmpus Avançado Jaguarão',
  'Câmpus Avançado Novo Hamburgo',
  'Campus Avançado Arcos',
  'Campus Avançado Boca do Acre',
  'Campus Avançado Bom Sucesso',
  'Campus Avançado Bonfim',
  'Campus Avançado Carolina',
  'Campus Avançado Catalão',
  'Campus Avançado Cataguases',
  'Campus Avançado Conselheiro Lafaiete',
  'Campus Avançado de Diamantino',
  'Campus Avançado de Guarantã do Norte',
  'Campus Avançado de Jaguaruana',
  'Campus Avançado de Lucas do Rio Verde',
  'Campus Avançado de Mombaça',
  'Campus Avançado de Sinop',
  'Campus Avançado Dirceu Arcoverde',
  'Campus Avançado Hidrolândia',
  'Campus Avançado Ipameri',
  'Campus Avançado Ipatinga',
  'Campus Avançado Itabirito',
  'Campus Avançado José De Freitas',
  'Campus Avançado Manacapuru',
  'Campus Avançado Piumhi',
  'Campus Avançado Pio IX',
  'Campus Avançado Ponte Nova',
  'Campus Avançado Porto Franco',
  'Campus Avançado Rosário',
  'Campus Avançado Tangará da Serra',
  'Campus Avançado Ubá',
  'Campus Avançado Uberaba Parque Tecnológico',
  'Cefor',
  'Centro de Referência de Pedra Branca do Amapari',
  'Polo de Inovação',
  'Polo de Inovação Campos Dos Goytacazes',
  'Polo de Inovação Salvador',
  'Reitoria',
].sort();

export interface SelectOption {
  value: string;
  label: string;
}

export const CAMPUS_OPTIONS: SelectOption[] = CAMPUS_LIST.map((campus) => ({
  value: campus,
  label: campus,
}));
